config/routes.rb
Portfolio::Application.routes.draw do
 
	root 'welcome#index'

	# resource :welcome, only: [:index]

	resources :projects, only: [:index]

	resources :experiences, only: [:index]

	resources :contacts, only: [:index]

	namespace :json, constraints: { format: 'json' } do

		resources :sections 
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def index

	end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

	def index

	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index

	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<h1 class="page-title">Contact</h1>

<article class="contact-info">
<h2 clas="contact">Email</h2>
<p>justinkemmerer@gmail.com</p>
</article>

<article class="contact-info">
<h2 clas="contact">Cell</h2>
<p>912.503.8215</p>
</article>

<article class="contact-info">
<h2 clas="contact">Google Voice</h2>
<p>908.240.0339</p>
</article>

<article class="contact-info">
<h2 clas="contact">Github</h2>
<p><a href="https://github.com/JustinGA">JustinGA</a></p>
</article>

<article class="contact-info">
<h2 clas="contact">Linkedin</h2>
<p><a href="http://www.linkedin.com/in/kemmererjustin">http://www.linkedin.com/in/kemmererjustin</a></p>
</article>

app/views/experiences/index.html.erb
<h1 class="page-title">experiences</h1>

<h2>H2</h2>

<h3>H3</h3>

<h4>H4</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Justin Kemmerer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
  <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono' rel='stylesheet' type='text/css'>
</head>
<body>
	<header>
		<div id="name">
			<%= render "layouts/name" %>
		</div>

		<nav>
			<ul id="navlist">
				<li id="about"><%= link_to "About", root_path %></li>
				<li><%= link_to "Projects", projects_path %></li>
				<!-- <li><%= link_to("Experience", experiences_path) %></li> -->
				<li><%= link_to "Contact", contacts_path %></li>
			</ul>
		</nav>
	</header>

<section id="content-container" >
	<%= yield %>
</section>

<footer>
	<p id="copyright">&copy; 2014 Justin Kemmerer.</p>
</footer>

</body>
</html>

app/views/projects/index.html.erb
<h1 class="page-title">Projects</h1>

<article class="project">
	<h2>Glass Events</h2>
	<h3>Group event planner focusing on transparency.</h2>
	<p>First project during the Web Development Immersive at General Assembly.  Focus for the project was Ruby on Rails and data modeling.</p>
	
	<h4>Features</h4>
	<ul>
		<li>Allows users to track the progress of the planning of an event.</li>
		<li>Users can see which event organizers are fullfiling certain tasks.</li>
		<li>Users can see quotes for services being considered.</li>
		<li>Users can track event costs as providers are chosen for each service.</li>
	</ul>

	<h4>Technical Features</h4>
	<ul>
		<li>Custom user authorizations, featuring multiple user levels.</li>
		<li>Strong data model, tracking all user interacation with the event planning process.</li>
		<li>Ruby on Rails, HTML, CSS, Foundation Framework.</li>
	</ul>
	
	<h4>Resources</h4>
	<ul class="resources">
		<li><%= link_to "Project", "http://glassevents.herokuapp.com/", :target => "_blank" %></li>
		<li><%= link_to "Github Repo", "https://github.com/JustinGA/glassevents", :target => "_blank" %></li>
	</ul>
</article>

<article class="project">
	<h2>HTML5 Picross</h2>
	<h3>Logic based puzzle game.</h2>
	<p>Final project during the Web Development Immersive at General Assembly.  Open-ended project to use technologies learned during the course.</p>

	<h4>Features</h4>
	<ul>
		<li>Users use the provided numbers to decypher which cells in the grid are filled.</li>
		<li>Users can flag cells to assist in decyphering the board.</li>
		<li>A completely puzzle board will then form a picture.</li>
		<li>Logic and features similar to Sudoku and Minesweeper.</li>
	</ul>

	<h4>Technical Features</h4>
	<ul>
		<li>Puzzle board built in served on the backend.</li>
		<li>JavaScript retrieves the puzzle key via AJAX request, then monitors the gameboard interactions and compares them against the puzzle key. </li>
		<li>Ruby on Rails, HTML, CSS, JavaScript, jQuery, Underscore.js, AJAX.</li>
	</ul>
	
	<h4>Resources</h4>
	<ul class="resources">
		<li><%= link_to "Project", "http://gapicross.herokuapp.com/", :target => "_blank" %></li>
		<li><%= link_to "Github Repo", "https://github.com/JustinGA/Picross", :target => "_blank" %></li>
	</ul>
</article>

<article class="project">
	<h2>AnyQuestions</h2>
	<h3>Classroom tool for asking questions.</h2>
	<p>Real-time tool for making sure the most common questions are answered while letting the instructor control the flow of the lesson.</p>

	<h4>Features</h4>
	<ul>
		<li>Students ask questions which are then updated for all students in realtime.</li>
		<li>Other students can upvote any questions that they also have.</li>
		<li>The question list will resort based on the most common questions.</li>
		<li>Instructor can monitor the question list and decide if a question needs to be answered before continuing on, or if they should come back to the question at a later time.</li>
		<li>Once a question has been answered it can be dismissed by the instructor.</li>
	</ul>

	<h4>Technical Features</h4>
	<ul>
		<li>Single page application updated in real time via AJAX requests.</li>
		<li>Custom JavaScript MVC adds and removes questions, tracks questions' upvotes, and maintains proper sorting of questions in real time.</li>
		<li>Ruby on Rails, HTML, CSS, JavaScript, custom JavaScript MVC, jQuery, Underscore.js, AJAX.</li>
	</ul>
	
	<h4>Resources</h4>
	<ul class="resources">
		<li hidden><a href="url">Project</a></li>
		<li><%= link_to "Github Repo", "https://github.com/JustinGA/AnyQuestions", :target => "_blank" %></li>
	</ul>
</article>

app/views/welcome/index.html.erb
<h1 class="page-title">About Justin</h1>

<h2>My Journey</h2>

<p>I'm a technologist with 10 years experience in the IT industry, having worked in a variety of positions.  My most recent position was as an IT Manager in an award winning call center in Savannah, GA.</p>

<p>In early 2013, I decided to supplement my existing technical skills by strengthening them where I felt there were weakest—programming.  This lead me to enrolling in General Assembly's Web Development Immersive course.  Over the next 12 weeks I spent all day, every day, learning to program in Ruby on Rails, JavaScript, and HTML5.  Along the way I found a new love in coding, and decided to make the full career shift from IT to development.</p>

<p>Now in 2014, a General Assembly graduate, I'm continuing on my new path of life-long learning; excited by the challenges I'll overcome and new things I'll discover along the way. </p>

<h2>Skills</h2>

<p>At General Assembly I studied and worked with a variety of technologies and techniques, in addition to the core of Ruby on Rails, JavaScript, HTML, and CSS.  Agile development methodolgies.  Modern web development conventions and techniques including writing Object Oriented and DRY code, RESTful architecture, and single-page applications using AJAX.  JavaScript libraries such as jQuery, jQueryUI, Underscore.js, and Backbone.js.  Additionally, while working on project applications, I found myself developing custom user authorizations, and an application specific custom JavaScript MVC.</p>

<p>Going forward, I am dedicating myself to expanding my knowledge of unit testing with frameworks such as RSPEC, and exploring the depth of what can be done in HTML5 and data visualization by using Canvas with D3.js; all while making sure to write better code.</p>